#!/bin/sh
/usr/bin/afew --tag --new --verbose

# 'notmuch tag' auto-excludes messages tagged with exclude_tags (deleted or spam)
notmuch tag -inbox +deleted "folder:uberspace/Trash"
notmuch tag -inbox +spam "folder:uberspace/Spam"
notmuch tag -inbox "folder:uberspace/Archive AND tag:inbox"
notmuch tag +sent "folder:uberspace/Sent AND (NOT tag:sent)"

/usr/bin/afew --move --verbose
