#!/bin/sh
echo
echo
echo Calling afew to tag new messages
$HOME/.local/bin/afew --tag --new --verbose
echo
echo
echo Manually tagging non-new messages that were moved to Archive, Junk, Trash, etc. on other client.
notmuch tag -inbox -autoinbox +deleted "folder:gandi/Trash AND (tag:inbox OR tag:autoinbox)"
notmuch tag -inbox -autoinbox +spam "folder:gandi/Junk AND (tag:inbox OR tag:autoinbox)"
notmuch tag -inbox -autoinbox "folder:gandi/Archives AND (tag:inbox OR tag:autoinbox)"
echo
echo
echo Calling afew to move messages from INBOX to Archive, Junk, Trash, etc.
$HOME/.local/bin/afew --move --verbose
echo
echo
echo Finished notmuch post-new hook
